### ISSUE TITLE
Error with Linen Cape multiple projectiles possibly due to EpicLoot Tripple shot enchant

### ISSUE THREAD

**Issue by Jester2020** [Happydragun4now/DragoonCapes#9]
[Here is the error. Happened while shooting a Gjall with an enchanted Skystrike bow. First time seeing it. Will try to reproduce it. I can't confirm that it's multiplying the already enchanted tripple shot or if they just ignore each other.

Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.einherjarCape.Proj_Setup_Prefix (Projectile __instance) (at <a118b6598411425cbd0f3d8aee1cc8a1>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::Setup>(Projectile,Character,UnityEngine.Vector3,single,HitData,ItemDrop/ItemData,ItemDrop/ItemData)
Radiator+<UpdateLoop>d__2.MoveNext () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)

[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero
[Info   : Unity Log] Look rotation viewing vector is zero

**Comment by Happydragun4now** [comment]
Hey Jester this error code was caused by the einherjar cape code (that checks when projectiles are fired), I implemented a safeguard for that so hopefully this is fixed with the next update but I can't say for sure as I wasn't able to reproduce this problem

**Comment by Jester2020** [comment]
The bow i was using already had Triple shot on it from EpicLoot. I wasn't using the einjerjar cape, i was wearing the Linen cape. I thought it might be a conflict between the cape and enchant both attempting to add extra projectiles. I still have the seed saved where the issue occured I can try to reproduce the issue.

**Comment by Happydragun4now** [comment]
The patch for the cape still runs regardless, of whether the cape is in the world or not, something maybe was given a random status effect that was the cape's effect? Either way 1.2.91 should fix this

**Comment by Jester2020** [comment]
Sounds great. I'll try to test it when I can.

**Comment by Jester2020** [comment]
Doesn't seem to be erroring with and without a bow with Tripple shot. So i think you can close this one as of the latest release.

**Comment by Happydragun4now** [comment]
Thanks Jester! Maybe this was the safeguards I added. Nobody else reported it so I'll close it for now
